### ISSUE TITLE
Add Mint support

### ISSUE THREAD

**Issue by uhooi** [fromkk/SpellChecker#2]
`Package.swift`  に `products` を追加することで、Mintに対応できます。
参考： [Add mint support · mac-cain13/R.swift@3158a81](https://github.com/mac-cain13/R.swift/commit/3158a813cfffceb5364abcd42f4e288fe86a56a3)

```diff:Package.swift
let package = Package(
    name: "SpellChecker",
+   products: [
+       .executable(name: "SpellChecker", targets: ["SpellChecker"])
+   ],
    dependencies: [
```

上記の対応により、Mintで使えるようになることを確認できました。
しかし、Mintを経由すると `-yml` オプションで指定したパスが取得できなくなります。

```diff:main.swift
+       let ymlPath = Commands.value(of: "yml")
+       print("ymlPath: \(String(describing: ymlPath))")
+       if let ymlPath = ymlPath {
-       if let ymlPath = Commands.value(of: "yml") {
```

```shell-session
$ mint run uhooi/SpellChecker@0.0.5 SpellChecker -yml {YAMLファイル} -- {対象ファイル}
…
ymlPath: nil
```

少し調査しただけでは解決できなかったので、PRでなくIssueとして報告します。
GitHub上のOSSにIssueを記載したことがないため、暗黙的なルールに反していたらご指摘いただけると嬉しいです。
よろしくお願いします。

**Comment by fromkk** [comment]
@uhooi ありがとうございます！どうもMintを通すと `-` の引数が分割されるみたいですね。。
`--` のprefixに変えようかと思いますが大丈夫でしょうか？

**Comment by fromkk** [comment]
@uhooi タグを `0.0.3` で打っておいたので `-yml` を `--yml` にして試して頂けるとかと思います。

例: `mint run fromkk/SpellChecker@0.0.3 SpellChecker -yml ${yml_path} -- ${files}`

**Comment by uhooi** [comment]
@fromkk prefixは `--` で問題ありません！
`--yml` で試して問題なく動作しました！

Mintの仕様なのか不具合なのか、気になりますね、、

**Comment by fromkk** [comment]
そうですねー、とりあえず今インストールしてくれている人には影響ないですが、もしアップデートした時にちょっと動作変わっちゃうのが気になりますがしょうがないですね。。
マージしたのでこのIssueもクローズさせていただきます！
ありがとうございました！
